#define PERSON 0
#define PERSON_ID 0
#define PERSON_NAME 1
#define PERSON_ISBLOCKED 2

#define COMPANY 1
#define COMPANY_ID 0
#define COMPANY_NAME 1
#define COMPANY_ISBLOCKED 2

#define ACCOUNT 2
#define ACCOUNT_ID 0
#define ACCOUNT_CREATETIME 1
#define ACCOUNT_ISBLOCKED 2
#define ACCOUNT_TYPE 3

#define LOAN 3
#define LOAN_ID 0
#define LOAN_AMOUNT 1
#define LOAN_BALANCE 2

#define MEDIUM 4
#define MEDIUM_ID 1
#define MEDIUM_ISBLOCKED 2
#define MEDIUM_TYPE 3

#define TRANSFER 5
#define TRANSFER_TIMESTAMP 0
#define TRANSFER_AMOUNT 1
#define TRANSFER_TYPE 2

#define WITHDRAW 6
#define WITHDRAW_TIMESTAMP 0
#define WITHDRAW_AMOUNT 1

#define REPAY 7
#define REPAY_TIMESTAMP 0
#define REPAY_AMOUNT 1

#define DEPOSIT 8
#define DEPOSIT_TIMESTAMP 0
#define DEPOSIT_AMOUNT 1

#define SIGNIN 9
#define SIGNIN_TIMESTAMP 0

#define INVEST 10
#define INVEST_TIMESTAMP 0
#define INVEST_RATIO 1

#define WORKIN 11

#define OWN 12

#define APPLY 13
#define APPLY_TIMESTAMP 0

#define GUARANTEE 14
#define GUARANTEE_TIMESTAMP 0

